version: '3.3'

services:
  app:
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
    restart: always
    volumes:
    - ./frontend:/app
    #- /app/node_modules
    #- /app/.next
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - NODE_ENV=development
    expose: 
      - 3000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
    command: sh -c "ollama serve & uv run uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
    - ./backend/app:/app
    environment:
      DEBUG: 1
    ports:
      - "127.0.0.1:8000:8000"
    expose: 
      - 8000